package com.bcan.sprintplanner.themes

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3B693A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFBCF0B4)
val onPrimaryContainerLight = Color(0xFF002204)
val secondaryLight = Color(0xFF3B6939)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBCF0B4)
val onSecondaryContainerLight = Color(0xFF002204)
val tertiaryLight = Color(0xFF246A4B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFABF2CA)
val onTertiaryContainerLight = Color(0xFF002113)
val errorLight = Color(0xFF904A48)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD8)
val onErrorContainerLight = Color(0xFF3B080A)
val backgroundLight = Color(0xFFF7FBF1)
val onBackgroundLight = Color(0xFF181D17)
val surfaceLight = Color(0xFFF6FAFE)
val onSurfaceLight = Color(0xFF171C1F)
val surfaceVariantLight = Color(0xFFDDE5DA)
val onSurfaceVariantLight = Color(0xFF414941)
val outlineLight = Color(0xFF717971)
val outlineVariantLight = Color(0xFFC1C9BF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3134)
val inverseOnSurfaceLight = Color(0xFFEDF1F5)
val inversePrimaryLight = Color(0xFFA0D39A)
val surfaceDimLight = Color(0xFFD6DADE)
val surfaceBrightLight = Color(0xFFF6FAFE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F8)
val surfaceContainerLight = Color(0xFFEAEEF2)
val surfaceContainerHighLight = Color(0xFFE5E9ED)
val surfaceContainerHighestLight = Color(0xFFDFE3E7)